name: Auto Home Gallery

on:
  schedule:
    - cron: '*/30 * * * *' # ogni 30 minuti
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch images from APIs
        run: |
          curl "https://api.unsplash.com/search/photos?query=jdm+car+night&per_page=5&client_id=1yLiYWVhE_HAY7MxFPGo3B4-9WfzmWj1R-VPaBTbNVA" > unsplash.json
          curl -H "Authorization: 2xbI4WF3YWnE66DEPr6gEJCNh4iuMyknemXRxw8WAanVE3kSMflm0KmD" "https://api.pexels.com/v1/search?query=jdm+car+night&per_page=5" > pexels.json

      - name: Merge JSON
        run: |
          node -e "
          const fs = require('fs');

          const u = JSON.parse(fs.readFileSync('unsplash.json')).results || [];
          const p = JSON.parse(fs.readFileSync('pexels.json')).photos || [];

          const data = [];

          u.forEach(i => data.push({
            img: i.urls.regular,
            url: i.links.html
          }));

          p.forEach(i => data.push({
            img: i.src.large,
            url: i.url
          }));

          fs.writeFileSync('home-gallery.json', JSON.stringify(data.slice(0,10), null, 2));
          "

      - name: Commit changes
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add home-gallery.json
          git commit -m "auto update gallery" || exit 0
          git push
