name: Update Gallery
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Versione aggiornata
      
      - name: Setup Node.js
        uses: actions/setup-node@v4 # Versione aggiornata
        with:
          node-version: '24' # Versione più recente

      - name: Fetch Photos
        run: node fetch_photos.js

      - name: Save Changes
        run: |
          git config --global user.name 'Robot-100Ottani'
          git config --global user.email 'robot@100ottani.com'
          git add gallery.json
          git commit -m "Nuove foto aggiunte automaticamente" || echo "Nessuna modifica"
          git push
